### ISSUE TITLE
Adding a comment fails with java.io.NotSerializableException: org.jenkinsci.plugins.pipeline.github.client.ExtendedIssueService

### ISSUE THREAD

**Issue by rombert** [jenkinsci/pipeline-github-plugin#55] opened 2019-02-01 23:53 UTC
I am using a scripted pipeline and trying to add an issue comment to the pull request. I have even tried to make the invocation from a `@NonCPS` method, but it still fails

```groovy
@NonCPS
def addPullRequestComment(def message) {
    pullRequest.comment(message)
}
```

The failing build can be seen at https://builds.apache.org/job/Sling/job/sling-whiteboard/job/PR-25/23/  and the log is here - [console.log](https://github.com/jenkinsci/pipeline-github-plugin/files/2823724/console.log).

**Comment by aaronjwhiteside** [comment] 2019-02-02 11:17
What version of the plugin are you using? I believe this was fixed in the latest 2.1 release.

**Comment by rombert** [comment] 2019-02-02 12:20
@aaronjwhiteside - can I find out without asking my Jenkins admin?

**Comment by rombert** [comment] 2019-02-07 09:57
@aaronjwhiteside - we are using version 2.1 already, confirmed in https://issues.apache.org/jira/browse/INFRA-17815 .

**Comment by barakwei** [comment] 2019-02-14 13:12
I see the exact same failure.
```
00:04:09.302  an exception which occurred:
00:04:09.302  	in field org.jenkinsci.plugins.pipeline.github.IssueCommentGroovyObject.issueService
00:04:09.302  	in object org.jenkinsci.plugins.pipeline.github.IssueCommentGroovyObject@5bed0993
00:04:09.302  	in field com.cloudbees.groovy.cps.Outcome.normal
00:04:09.302  	in object com.cloudbees.groovy.cps.Outcome@5f15a3a2
00:04:09.302  	in field org.jenkinsci.plugins.workflow.cps.steps.ParallelStep$ResultHandler.outcomes
...
00:04:09.302  Caused: java.io.NotSerializableException: org.jenkinsci.plugins.pipeline.github.client.ExtendedIssueService
```

So the field `issueService` in `IssueCommentGroovyObject` is not serializable (while `IssueCommentGroovyObject` is). But since the method is `@NonCPS` why does the serialization happen?

**Comment by aaronjwhiteside** [comment] 2019-02-18 10:30
Just an FYI that I'm working on it and it should be solved in the next release

**Comment by barakwei** [comment] 2019-02-18 11:09
Thanks!
I don't think iterating causes this, but only posting comments. I managed to solve this by doing this:

```
@NonCPS
def rewritePullRequestComment(commentID, commentBody) {
  def newComment = pullRequest.editComment(commentID, commentBody)
  newComment = null
}
```

instead of 
```
pullRequest.editComment(commentID, commentBody)
```

**Comment by rombert** [comment] 2019-02-18 11:18
We did something similar and return the comment's id instead of the comment from a `@NonCPS` function

https://github.com/apache/sling-tooling-jenkins/blob/094ff3c11d35f2e7ad80f44aa7a31cd1f48bdfe8/vars/slingOsgiBundleBuild.groovy#L96-L100

**Comment by aaronjwhiteside** [comment] 2019-02-21 09:24
I've released 2.3 which should fix this problem, please give it a test and let me know how it goes for you.

**Comment by rombert** [comment] 2019-02-21 09:50
Thanks for the fix @aaronjwhiteside ! I've asked for an upgrade of the plugin on our Jenkins instance, will let you know after that is done.

**Comment by AndreaGiardini** [comment] 2019-02-21 12:11
I can confirm that version 2.3 fixed the issue in my case

**Comment by aaronjwhiteside** [comment] 2019-02-23 10:42
This should be fixed now, if anyone still has a problem please feel free to reopen this issue.

**Closed by aaronjwhiteside** 2019-02-23 10:42 UTC
Labels: bug, help wanted

**Comment by kutzi** [comment] 2022-06-16 10:14
I'm seeing a similar issue:
```
an exception which occurred:
	in field com.cloudbees.groovy.cps.impl.FunctionCallEnv.locals
	in object com.cloudbees.groovy.cps.impl.FunctionCallEnv@1dec925f
	in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
	in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@8213b10
	in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
	in object com.cloudbees.groovy.cps.impl.LoopBlockScopeEnv@6c78d977
	in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
	in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@d0f1ec8
	in field com.cloudbees.groovy.cps.impl.CallEnv.caller
	in object com.cloudbees.groovy.cps.impl.ClosureCallEnv@6410a0ce
	in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
	in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@49b39e0e
	in field com.cloudbees.groovy.cps.impl.CallEnv.caller
	in object com.cloudbees.groovy.cps.impl.FunctionCallEnv@2f0041cf
	in field com.cloudbees.groovy.cps.Continuable.e
	in object org.jenkinsci.plugins.workflow.cps.SandboxContinuable@3f22a268
	in field org.jenkinsci.plugins.workflow.cps.CpsThread.program
	in object org.jenkinsci.plugins.workflow.cps.CpsThread@1792ad38
	in field org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.threads
	in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@49536d0b
	in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@49536d0b
Also:   hudson.AbortException: script returned exit code 2
		at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:664)
		at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:610)
		at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:554)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
Caused: java.io.NotSerializableException: org.jenkinsci.plugins.pipeline.github.PullRequestGroovyObject$$Lambda$1780/0x00000001015cf840
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:274)
	at org.jboss.marshalling.river.BlockMarshaller.doWriteObject(BlockMarshaller.java:65)
```

Not really good reproducable. Happens from time to time, but I didn't yet recognise a pattern
Will check if @NonCPS fixes it.

**Comment by kuzaxak** [comment] 2023-07-03 06:38
We have the same:

```
 Caused: java.io.NotSerializableException: org.jenkinsci.plugins.pipeline.github.PullRequestGroovyObject$$Lambda$1761/0x0000000804024040
17:19:53  	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:274)
17:19:53  	at org.jboss.marshalling.river.BlockMarshaller.doWriteObject(BlockMarshaller.java:65)
17:19:53  	at org.jboss.marshalling.river.BlockMarshaller.writeObject(BlockMarshaller.java:56)
17:19:53  	at org.jboss.marshalling.MarshallerObjectOutputStream.writeObjectOverride(MarshallerObjectOutputStream.java:50)
17:19:53  	at org.jboss.marshalling.river.RiverObjectOutputStream.writeObjectOverride(RiverObjectOutputStream.java:179)
17:19:53  	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:341)
17:19:53  	at java.base/java.util.HashMap.internalWriteEntries(HashMap.java:1858)
```

@aaronjwhiteside can we reopen the ticket?
