### ISSUE TITLE
Convert Error when use removeLabel method on Declarative.

### ISSUE THREAD

**Issue by darkrasid** [jenkinsci/pipeline-github-plugin#26] opened 2018-07-04 10:28 UTC
Hi. 
First Thank you for developing this plugin.

I try to remove label on Declarative pipeline but it occur convert(json=> string) error.

Am I miss something?
Please, give me a hint.

My Jenkins file
```
pipeline {
  agent any 

  stages {
  

    stage('build') {
      when {
        allOf {
          branch 'PR-*'
        }
      }

      steps {
        sh 'echo build3'
        script {
          def b = "Build Failed"
          pullRequest.addAssignees(["pilsner-suh"]) // works well
          pullRequest.addLabels(["help wanted"]) // also works well
          pullRequest.removeLabel(b.toString()) // occur error
          pullRequest.removeLabel(b) // also occur error
          pullRequest.removeLabel("Build Failed") // also occur error
        }
      }
    }
  }
}
```

And full trace
```
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
Caused: com.google.gson.JsonSyntaxException
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at org.eclipse.egit.github.core.client.GitHubClient.parseJson(GitHubClient.java:453)
Caused: java.io.IOException: Parse exception converting JSON to object
	at org.eclipse.egit.github.core.client.GitHubClient.parseJson(GitHubClient.java:455)
	at org.eclipse.egit.github.core.client.GitHubClient.parseJson(GitHubClient.java:434)
	at org.eclipse.egit.github.core.client.GitHubClient.parseError(GitHubClient.java:545)
	at org.eclipse.egit.github.core.client.GitHubClient.delete(GitHubClient.java:828)
	at org.eclipse.egit.github.core.client.GitHubClient.delete(GitHubClient.java:626)
	at org.jenkinsci.plugins.pipeline.github.client.ExtendedIssueService.removeLabel(ExtendedIssueService.java:141)
	at org.jenkinsci.plugins.pipeline.github.PullRequestGroovyObject.removeLabel(PullRequestGroovyObject.java:458)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:157)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:133)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:155)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:159)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
Caused: java.io.UncheckedIOException
	at org.jenkinsci.plugins.pipeline.github.PullRequestGroovyObject.removeLabel(PullRequestGroovyObject.java:460)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:157)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:133)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:155)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:159)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at WorkflowScript.run(WorkflowScript:20)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:82)
	at sun.reflect.GeneratedMethodAccessor305.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:60)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:77)
	at sun.reflect.GeneratedMethodAccessor307.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:261)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$101(SandboxContinuable.java:34)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.lambda$run0$0(SandboxContinuable.java:59)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:58)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:174)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:332)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:83)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:244)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:232)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by aaronjwhiteside** [comment] 2018-07-13 06:01
So the error is happening when the `GitHubClient` is trying to unmarshall an error response. It was expecting a json response but got something else..

**Comment by longwave** [comment] 2019-01-29 09:44
I have also run into this. I added an extra log recorder to Jenkins to capture `sun.net.www.protocol.http.HttpURLConnection` and here is the HTTP request and response with sensitive data redacted:

```
Jan 29, 2019 9:38:14 AM FINE sun.net.www.protocol.http.HttpURLConnection

sun.net.www.MessageHeader@671c6e816 pairs:
{DELETE /repos/[redacted]/[redacted]/issues/38/labels/Needs rebuild HTTP/1.1: null}
{Authorization: Basic [redacted]}
{User-Agent: GitHubJava/2.1.0}
{Accept: application/vnd.github.v3.full+json}
{Host: api.github.com}
{Connection: keep-alive}

Jan 29, 2019 9:38:15 AM FINE sun.net.www.protocol.http.HttpURLConnection

sun.net.www.MessageHeader@589cefef4 pairs:
{null: HTTP/1.0 400 Bad Request}
{Cache-Control: no-cache}
{Connection: close}
{Content-Type: text/html}
```

**Comment by longwave** [comment] 2019-01-29 09:54
Looks like the problem is around escaping spaces in the label name; if I try a label without spaces it works:

```
Jan 29, 2019 9:51:57 AM FINE sun.net.www.protocol.http.HttpURLConnection

sun.net.www.MessageHeader@77d944de6 pairs:
{DELETE /repos/[redacted]/[redacted]/issues/38/labels/Needs-rebuild HTTP/1.1: null}
{Authorization: Basic [redacted]}
{User-Agent: GitHubJava/2.1.0}
{Accept: application/vnd.github.v3.full+json}
{Host: api.github.com}
{Connection: keep-alive}

Jan 29, 2019 9:51:57 AM FINE sun.net.www.protocol.http.HttpURLConnection

sun.net.www.MessageHeader@3e2f8a5121 pairs:
{null: HTTP/1.1 404 Not Found}
{Server: GitHub.com}
{Date: Tue, 29 Jan 2019 09:51:57 GMT}
{Content-Type: application/json; charset=utf-8}
{Content-Length: 132}
{Status: 404 Not Found}
...
```

The 404 is expected here as the label wasn't set on the pull request.

**Comment by longwave** [comment] 2019-01-29 10:00
`searchIssues` in the parent class does this to encode the search 

```
final String encodedQuery = URLEncoder.encode(query, CHARSET_UTF8)
	.replace("+", "%20") //$NON-NLS-1$ //$NON-NLS-2$
	.replace(".", "%2E"); //$NON-NLS-1$ //$NON-NLS-2$
uri.append('/').append(encodedQuery);
```

I imagine something similar is needed here?

**Comment by aaronjwhiteside** [comment] 2019-01-29 10:02
Thanks @longwave, I've taken a look at the Eclipse GitHub client used in the project and it seems to be inconsistent in it's approach to URL encoding, `LabelService.deleteLabel()` just appends the label passed in to the url..

**Comment by aaronjwhiteside** [comment] 2019-01-29 10:09
Fixed in https://github.com/jenkinsci/pipeline-github-plugin/commit/c03464ef0ddf1568c0c7d06aea2d36d59b41bf39

**Closed by aaronjwhiteside** 2019-01-29 10:09 UTC
Labels: help wanted
